### ISSUE TITLE
Feature Request - Add environment Info to return.

### ISSUE THREAD

**Issue by Rucknar** [infinityworksltd/prometheus-rancher-exporter#2]
For running multiple ones of these, we need to either:
* Prefix environment (compute cluster) name to the stack/service/hostname output
* Add a new field with the environment listed

As highlighted in https://github.com/infinityworksltd/prom-conf/issues/2

**Comment by Rucknar** [comment]
@JamesBarwell You think this might be an easy one we can knock off?

**Comment by JamesBarwell** [comment]
Should be easy if we can get the environment name passed into the node process somehow. Could it be made available as an environment variable by adjusting the docker-compose file?

I'm thinking that exposing it as a label would be better than trying to insert it into the variable name. I'd prefer to keep the metric names static, which as far as I'm aware is how every other exporter does it.

**Comment by Rucknar** [comment]
Indeed, labels are probably the best bet here. We can populate with the details within the API, it should be listed on each object as a parent.

**Comment by jmatsushita** [comment]
FYI I'd would like this feature too. In the meantime I worked around it with relabeling:

```
- job_name: 'rancher-api'
  static_configs:
    - targets:
      - 'prometheus-rancher-exporter:9010' 
      - 'prometheus-rancher-exporter.prometheus-agents.dev.another.org:9010'
      - 'prometheus-rancher-exporter.prometheus-agents.staging.another.org:9010'
      - 'prometheus-rancher-exporter.prometheus-agents.prod.example.org:9010'
  metric_relabel_configs:                                                        
  - source_labels: ['instance']                                                           
    target_label:  'environment'                                                          
    regex: '(.*)prometheus-agents\.(.*?)\.(example|another)(.*)'              
    replacement:  $2    
```

In case it helps someone else !
