### ISSUE TITLE
No Rancher stats with v1.5.9

### ISSUE THREAD

**Issue by dalareo** [infinityworksltd/prometheus-rancher-exporter#22]
I have installed Prometheus from Rancher Catalog but though I can get stats from hosts and containers I get no stats from Rancher. I setup Cattle_url and api credentials in prometheus-rancher-exporter and enabled rancher/server environment and ports.

My log:

```
5/10/2017 6:52:56 PMINFO[0602] Metrics successfully processed for services
5/10/2017 6:52:56 PMINFO[0602] Scraping: http://MY_IP/v2-beta/hosts/
5/10/2017 6:52:56 PMINFO[0602] Metrics successfully processed for hosts
```

My prometheus config:

```
global:                                                                         
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:                                                              
      monitor: 'exporter-metrics'                                                
                                                                                
scrape_configs:

- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 15s
    type: A
    port: 9100

- job_name: 'ContainerMetrics'
  static_configs:
    - targets:
      - 'MY_RANCHER_IP:9108'

- job_name: 'RancherServerMetrics'
  dns_sd_configs:
  - names:
    - cadvisor
    refresh_interval: 15s
    type: A
    port: 8080

- job_name: 'RancherApi'
  dns_sd_configs:
  - names:
    - 'prometheus-rancher-exporter'
    refresh_interval: 15s
    type: A
    port: 9173

- job_name: 'Prometheus'
  static_configs:
    - targets:
      - '127.0.0.1:9090'
```
